site_name: Notes AI & Ollama
site_url: https://alexandrdragunkin.github.io/notes_ai_ollama/
repo_url: https://github.com/AlexandrDragunkin/notes_ai_ollama
repo_name: GitHub
theme:
  name: material
plugins:
  - search
  - myst_parser
nav:
  - Home: index.myst
